apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shift-api
  name: shift-api
  namespace: default
spec:
  replicas: 3
  minReadySeconds: 45
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: shift-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: shift-api
    spec:
      containers:
        - image: felipetexa/shifts-api:0.0.1.RELEASE
          imagePullPolicy: IfNotPresent
          name: shifts-api
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: shift-api
  name: shift-api
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.36.6.242
  clusterIPs:
    - 10.36.6.242
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 30987
      port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: shift-api
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 35.202.82.147
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shift-api
  namespace: default

spec:
  maxReplicas: 10
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization
      type: Resource
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shift-api
